apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: {{ .Values.llmd.namespace }}
  labels:
    llm-d.ai/model: {{ printf "ms-%s-llm-d-modelservice" .Values.wva.baseName }}
spec:
  selector:
    llm-d.ai/model: {{ printf "ms-%s-llm-d-modelservice" .Values.wva.baseName }}
  ports:
    - name: vllm
      port: 8200
      protocol: TCP
      targetPort: 8200
      nodePort: {{ .Values.vllmService.nodePort }}
  type: NodePort
