# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-manager-metrics-monitor
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: inferno-autoscaler
    app.kubernetes.io/managed-by: kustomize
spec:
  endpoints:
  - port: https
    path: /metrics
    interval: 10s
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: inferno-autoscaler
  namespaceSelector:
    matchNames:
    - system
