apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: vllme-deployment-hpa
  namespace: llm-d-sim
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vllme-deployment
  minReplicas: 0  # scale to zero - alpha feature
  maxReplicas: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      # When the metrics indicate that the target should be scaled up, the algorithm looks into previously computed desired states, and uses the highest value from the specified interval.
      # In the above example, all desired states from the past 60 seconds will be considered.
      policies:
      - type: Pods
        value: 10
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 0
      # When the metrics indicate that the target should be scaled down, the algorithm looks into previously computed desired states, and uses the highest value from the specified interval.
      # In the above example, all desired states from the past 60 seconds will be considered.
      policies:
      - type: Pods
        value: 10
        periodSeconds: 15
  metrics:
  - type: External
    external:
      metric:
        name: inferno_desired_replicas
        selector:
          matchLabels:
            variant_name: vllme-deployment
      target:
        type: AverageValue
        averageValue: "1"
