apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

patches:
- path: prometheus-patch.yaml
  target:
    kind: Deployment
    name: controller-manager
namespace: inferno-autoscaler-test
