processors:
  crd:
    ignore:
      # Ignore k8s built-in types
      - "metav1.TypeMeta"
      - "metav1.ObjectMeta"
      - "metav1.ListMeta"
      - "runtime.RawExtension"
render:
  kubernetesVersion: 1.32
